version: "3"

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recept
    ports:
      - "3308:3306"
    volumes:
      - /mysqldb/volume:/var/lib/mysql
    restart: on-failure

  myadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "3307:80"
    restart: on-failure
    links:
      - mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/recept
    ports:
      - 8005:8002
    restart: on-failure
    links:
      - mysql
    depends_on:
      - mysql